### PR TITLE
Add missing colon

### PR DESCRIPTION
**Pull request by susiwen8**
Add missing colon in echarts.md

### CODE REVIEW

**Comment by plainheart** [comment]
LGTM.
But should we add a semicolon at the end of each line of property?
Just like this
```js
(dom: HTMLDivElement | HTMLCanvasElement, theme?: Object | string, opts?: {
    devicePixelRatio?: number;
    renderer?: string;
    width?: number | string;
    height?: number | string;
}) => ECharts
```

**Comment by susiwen8** [comment]
@plainheart Semicolon has been added

**Comment by plainheart** [comment]
All right~

**Comment by plainheart** [comment]
As the previous usage like [`echartsInstance.resize`](https://echarts.apache.org/en/api.html#echartsInstance.resize), maybe we should use comma but not semicolon, a tweak for this has been included by #116.

**Pull request merged**
