### PR TITLE
feat: added Chinese translation for coding-standard.

### PR DESCRIPTION
**Pull request by plainheart**
Chinese translation of  `coding-standard` is currently missing, this PR provides the first version. Some reviews and suggestions are expected to make it better.
There are also some work to be done on https://github.com/ecomfe/echarts-www. 
See ecomfe/echarts-www#4

### CODE REVIEW

**Comment by plainheart** [comment]
BTW, in current English version, on [Statement ](https://echarts.apache.org/en/coding-standard.html#statement) block, comma `,` here should be semicolon `;` ?

image

**Comment by pissang** [comment]
Hi @plainheart, sorry for the late reply. Indeed, it should be `semicolon`.

**Comment by Ovilia** [comment]
@plainheart Great job! Really appreciate it! 👍

**Comment by plainheart** [comment]
Hi there, this PR is related to https://github.com/ecomfe/echarts-www/pull/4. Please have a review for it if there is available time. Thank you~

**Pull request merged**
